version: 2
models:
  - name: test_joel
    description: Dynamic table created via CBA Migration Assistant for test_joel
    config:
      materialized: dynamic_table
      target_lag: 1 hour
      snowflake_warehouse: DEMO_WH
    meta:
      created_by: CBA_Migration_Assistant
      created_date: '2025-11-27'
      source: Teradata Migration
      target_database: CBA_DEMO
      target_schema: PUBLIC
